export const ADD_TODO = 'ADD_TODO';

export const TOGGLE_STATUS_TODO = 'TOGGLE_STATUS_TODO';

export const FILTER_SEARCH_TODO = 'FILTER_SEARCH_TODO';

export const FILTER_STATUS_TODO = 'FILTER_STATUS_TODO';

export const FILTER_PRIORITY_TODO = 'FILTER_PRIORITY_TODO';
